// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Jaihxi2ma3JFFO1Tfr5ZrNIgnj7eKq4',
    appId: '1:173620654175:web:6c0e94e379c58cef36abea',
    messagingSenderId: '173620654175',
    projectId: 'cnfpatel',
    authDomain: 'cnfpatel.firebaseapp.com',
    storageBucket: 'cnfpatel.firebasestorage.app',
    measurementId: 'G-GTJ13FEXC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO0GdFPdZaecUXe3YtFDohMOLpMuENAkg',
    appId: '1:173620654175:android:da2ea920283ede3536abea',
    messagingSenderId: '173620654175',
    projectId: 'cnfpatel',
    storageBucket: 'cnfpatel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtgjC9S8wHEy62WVx4cLqCDbEOffhL698',
    appId: '1:173620654175:ios:ec9b0ab48b35f28d36abea',
    messagingSenderId: '173620654175',
    projectId: 'cnfpatel',
    storageBucket: 'cnfpatel.firebasestorage.app',
    iosBundleId: 'com.example.cnfpatel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtgjC9S8wHEy62WVx4cLqCDbEOffhL698',
    appId: '1:173620654175:ios:ec9b0ab48b35f28d36abea',
    messagingSenderId: '173620654175',
    projectId: 'cnfpatel',
    storageBucket: 'cnfpatel.firebasestorage.app',
    iosBundleId: 'com.example.cnfpatel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Jaihxi2ma3JFFO1Tfr5ZrNIgnj7eKq4',
    appId: '1:173620654175:web:f93dcc2938c3c4fd36abea',
    messagingSenderId: '173620654175',
    projectId: 'cnfpatel',
    authDomain: 'cnfpatel.firebaseapp.com',
    storageBucket: 'cnfpatel.firebasestorage.app',
    measurementId: 'G-JRPM0VC9KH',
  );
}
